/* eslint-disable */

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import AuthContext from "./context/AuthContext"
import Navbar from '../component/ui/navbar'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={geistSans.className}>
      <meta
        name='viewport'
        content='minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover'
      />
      <body className="w-full max-w-screen-xl overflow-auto mx-auto">
        <main>{children}</main>
      </body>
    </html>
  );
}